server.port: 10002
spring.profiles.include: credentials

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

cloud:
  aws:
    credentials:
      access-key: TEST
      secret-key: TEST
    region:
      static: ap-northeast-2
    stack:
      auto: false

    # S3 설정
    s3:
      bucket: test-bucket-kimsiho

    # sns 설정
    sns:
      test-topic-arn: # sns topic arn

    # ses 설정
    ses:
      access-key: TEST
      secret-key: TEST