cloud:
  aws:
    credentials:
      access-key: AKIA3ZBLH2VP4HJZMHQX
      secret-key: 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
    # 공통의 credentials를 쓸 수도 있고 SES 전용 credentials를 쓸 수도 있음
    ses:
      access-key:
      secret-key:
