cloud:
  aws:
    credentials:
      access-key: AKIA3ZBLH2VPYW4AZXNP
      secret-key: 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
    # 공통의 credentials를 쓸 수도 있고 SES 전용 credentials를 쓸 수도 있음
    ses:
      access-key: AKIA3ZBLH2VPYW4AZXNP
      secret-key: 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