server.port: 9090

logging:
 level:
   root: info
   com.zaxxer.hikari.pool.HikariPool: debug
   org.springframework.web: info
   org.hibernate.SQL: debug
   org.hibernate.type: trace

#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url:
#    username:
#    password:
#    hikari:
#      maximum-pool-size: 1
#      minimum-idle: 1

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:jpadb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

    hibernate:
      ddl-auto: create

#      jdbc:
#        batch_size: 10

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# batch-fetch-size: 100  1000이하의 값을 디폴트 전역 설정으로 깔고 간다